### ISSUE TITLE
docker-compose to run the application in Production.

### ISSUE THREAD

**Issue by brianupskill** [kriasoft/nodejs-api-starter#99]
Can someone provide an example docker-compose that would run the container in production mode?

**Comment by cmmartin** [comment]
A simple example might look like this...

```yaml
version: '3'

services:
  nginx:
    restart: always
  api:
    environment:
      - NODE_ENV=production
      - CORS_ORIGIN=https://getlatka.com
    restart: always
  db:
    restart: always
  redis:
    restart: always

```

Then, if that file is named `production.yml`, you can run it like this...

```bash
docker-compose -f docker-compose.yml -f production.yml up
```

This will override the values in `docker-compose.yml` with the values in `production.yml`
